- hosts: all

  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
   
    vmware:
      host: '{{ lookup("env", "VCenter.Host") }}'
      username: '{{ lookup("env", "Username") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  
  tasks:
    - debug:
        var: machine
    - debug:
        var: vmware

    
